# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 02:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20170412_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='twitteruser',
            name='test',
            field=models.CharField(default=django.utils.timezone.now, max_length=50, verbose_name='test'),
            preserve_default=False,
        ),
    ]
