# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-16 02:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_twitteruser_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='twitteruser',
            name='test',
        ),
    ]
