# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 03:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_remove_twitteruser_test'),
    ]

    operations = [
        migrations.CreateModel(
            name='TwitterMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='content of a Twitter message')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_message', to='website.TwitterUser')),
            ],
        ),
        migrations.AlterField(
            model_name='directededge',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='source_edge', to='website.TwitterUser'),
        ),
        migrations.AlterField(
            model_name='directededge',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='target_edge', to='website.TwitterUser'),
        ),
    ]
