# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 03:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20170419_2355'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='twittermessage',
            table='twitter_message',
        ),
    ]
